apiVersion: dynamodb.aws.allianz.io/v1beta1
kind: Table
metadata:
  name: fh-sample-table
spec:
  forProvider:
    region: us-east-1
    attributeDefinitions:
      - attributeName: attribute1
        attributeType: S
    keySchema:
      - attributeName: attribute1
        keyType: HASH
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1
  providerConfigRef:
    name: example
  writeConnectionSecretToRef:
    name: fh-sample-table-secret
    namespace: crossplane-system